export const ErrorCodes = {
  // ── Auth / Security ──────────────────────────────────────────
  SEC_AUTH_TOKEN_MISSING: 'SEC_AUTH_TOKEN_MISSING',
  SEC_AUTH_TOKEN_EXPIRED: 'SEC_AUTH_TOKEN_EXPIRED',
  SEC_AUTH_INVALID_CREDENTIALS: 'SEC_AUTH_INVALID_CREDENTIALS',
  SEC_AUTH_INSUFFICIENT_PERMISSIONS: 'SEC_AUTH_INSUFFICIENT_PERMISSIONS',
  SEC_AUTH_SUPER_ADMIN_REQUIRED: 'SEC_AUTH_SUPER_ADMIN_REQUIRED',
  SEC_AUTH_PASSWORD_CHANGE_REQUIRED: 'SEC_AUTH_PASSWORD_CHANGE_REQUIRED',

  // ── User ─────────────────────────────────────────────────────
  ERR_USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  ERR_USER_EMAIL_EXISTS: 'ERR_USER_EMAIL_EXISTS',
  ERR_USER_CI_EXISTS: 'ERR_USER_CI_EXISTS',
  ERR_USER_CREATION_FAILED: 'ERR_USER_CREATION_FAILED',
  ERR_USER_UPDATE_FAILED: 'ERR_USER_UPDATE_FAILED',

  // ── Role ─────────────────────────────────────────────────────
  ERR_ROLE_NOT_FOUND: 'ERR_ROLE_NOT_FOUND',
  ERR_ROLE_BUILT_IN: 'ERR_ROLE_BUILT_IN',
  ERR_ROLE_NAME_EXISTS: 'ERR_ROLE_NAME_EXISTS',
  ERR_ROLE_CREATION_FAILED: 'ERR_ROLE_CREATION_FAILED',
  ERR_ROLE_UPDATE_FAILED: 'ERR_ROLE_UPDATE_FAILED',
  ERR_ROLE_ASSIGNMENT_FAILED: 'ERR_ROLE_ASSIGNMENT_FAILED',

  // ── Institution ──────────────────────────────────────────────
  ERR_INSTITUTION_NOT_FOUND: 'ERR_INSTITUTION_NOT_FOUND',
  ERR_INSTITUTION_UPDATE_FAILED: 'ERR_INSTITUTION_UPDATE_FAILED',

  // ── Program ──────────────────────────────────────────────────
  ERR_PROGRAM_NOT_FOUND: 'ERR_PROGRAM_NOT_FOUND',
  ERR_PROGRAM_CREATION_FAILED: 'ERR_PROGRAM_CREATION_FAILED',
  ERR_PROGRAM_UPDATE_FAILED: 'ERR_PROGRAM_UPDATE_FAILED',
  ERR_PROGRAM_DELETE_FAILED: 'ERR_PROGRAM_DELETE_FAILED',

  // ── Course ───────────────────────────────────────────────────
  ERR_COURSE_NOT_FOUND: 'ERR_COURSE_NOT_FOUND',
  ERR_COURSE_CREATION_FAILED: 'ERR_COURSE_CREATION_FAILED',
  ERR_COURSE_UPDATE_FAILED: 'ERR_COURSE_UPDATE_FAILED',
  ERR_COURSE_DELETE_FAILED: 'ERR_COURSE_DELETE_FAILED',

  // ── Term ─────────────────────────────────────────────────────
  ERR_TERM_NOT_FOUND: 'ERR_TERM_NOT_FOUND',
  ERR_TERM_ALREADY_ACTIVE: 'ERR_TERM_ALREADY_ACTIVE',
  ERR_TERM_CREATION_FAILED: 'ERR_TERM_CREATION_FAILED',
  ERR_TERM_UPDATE_FAILED: 'ERR_TERM_UPDATE_FAILED',
  ERR_TERM_CLOSE_FAILED: 'ERR_TERM_CLOSE_FAILED',
  ERR_TERM_DELETE_FAILED: 'ERR_TERM_DELETE_FAILED',

  // ── Section ──────────────────────────────────────────────────
  ERR_SECTION_NOT_FOUND: 'ERR_SECTION_NOT_FOUND',
  ERR_SECTION_CAPACITY_EXCEEDED: 'ERR_SECTION_CAPACITY_EXCEEDED',
  ERR_SECTION_SCHEDULE_CONFLICT: 'ERR_SECTION_SCHEDULE_CONFLICT',
  ERR_SECTION_CLOSED_TERM: 'ERR_SECTION_CLOSED_TERM',
  ERR_SECTION_CREATION_FAILED: 'ERR_SECTION_CREATION_FAILED',
  ERR_SECTION_UPDATE_FAILED: 'ERR_SECTION_UPDATE_FAILED',
  ERR_SECTION_DELETE_FAILED: 'ERR_SECTION_DELETE_FAILED',
  ERR_SCHEDULE_NOT_FOUND: 'ERR_SCHEDULE_NOT_FOUND',

  // ── Generic / Validation ─────────────────────────────────────
  ERR_VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',
  ERR_RESOURCE_NOT_FOUND: 'ERR_RESOURCE_NOT_FOUND',
  ERR_CONFLICT: 'ERR_CONFLICT',
  SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
